### ISSUE TITLE
location的持续计算

### ISSUE THREAD

**Issue by juqkai** [LiRenTech/project-graph-qt#11]
随便点击 WASD，会发现location会一直刷新，虽然减小幅度有减少的趋势，但这个过程还是会产生太多不不要的计算，同时会导致本来固定的画布，有轻微的飘逸

**Comment by Littlefean** [comment]
现在增加了物理设置，可以手动设置“摄像机移动的摩擦力”，移动的“动力大小”，减少漂移感

**Comment by zty012** [comment]
在1.0缩放的情况下，是不会有漂移的
