### ISSUE TITLE
当点击节点后，键盘移动视角，删除图标不会跟随移动，一直在原地显示

### ISSUE THREAD

**Issue by INT-TPLAN** [LiRenTech/project-graph-qt#22]
当点击节点后，键盘移动视角，删除图标不会跟随移动，一直在原地显示

**Comment by INT-TPLAN** [comment]
更新：删除图标似乎是根据框选后鼠标的末位置显示的，最好还是根据总体框选节点最小面积矩形右下角判断来好

**Comment by Littlefean** [comment]
这确实是一个严重的问题, 那个小垃圾筒图标太容易被点到了

**Comment by Littlefean** [comment]
已更改为所有选择的节点的外接矩形的右下角，并再向右下角平移一小段距离。
同时删除图标大小本身不跟随 画面缩放而改变（防止在极端的缩放条件下不好点击到图标）
