### ISSUE TITLE
為何無法開啟 windows

### ISSUE THREAD

**Issue by 123hi123** [LiRenTech/project-graph-qt#31]
![image](https://github.com/user-attachments/assets/5f90d594-d2d5-4c63-ab6f-5b8b3508b467)

**Comment by Littlefean** [comment]
![image](https://github.com/user-attachments/assets/9491fb69-48ea-4d37-ac8e-a30edff560ac)

这个路径可以完整发一下吗?

**Comment by 123hi123** [comment]
![image](https://github.com/user-attachments/assets/3a7283b9-dc6f-4dde-a37f-975d7cc5fbdc)

**Comment by Littlefean** [comment]
现在应该好了, 您可以试试再在README那里下载一下

**Comment by 123hi123** [comment]
謝 這就去試

**Comment by zty012** [comment]
已修复
