### ISSUE TITLE
为删除功能添加快捷键

### ISSUE THREAD

**Issue by clinlx** [LiRenTech/project-graph-qt#55]
建议为删除功能添加快捷键，推荐为“Delete”键

理由是：右键拖动删除只能删除一条直线上的内容，需要大面积删除内容还是要靠框选功能。但是框选后只能使用鼠标寻找并点击删除按钮，没有快捷键，使用起来十分难受。

另外，你这三个一模一样的删除垃圾桶图标是BUG吗？但只有最左边那个有功能。让我十分费解。

![image](https://github.com/user-attachments/assets/133e4133-0128-49e9-a196-c22f505d7390)

不过这不是汇报BUG，只是展示当前删除功能是点击这个按钮。

**Comment by Littlefean** [comment]
工具栏功能目前还没做好，只有一个删除功能，后续可能会增加一些对齐等按钮，这个最开始是测试工具栏的渲染，后面两个图标是占位用的
